default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ror_a_site2_development

test:
  <<: *default
  database: ror_a_site2_test

production:
  <<: *default
  database: ror_a_site2_production
  username: ror_a_site2
  password: <%= ENV['ROR_A_SITE2_DATABASE_PASSWORD'] %>
